=== Fedict/eid-test-cards/pcsccontrol/control.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>
      This file keeps track of which virtual card to use for a certain physical test card.
      The physical test card is representated by it's chip number, the file element contains
      the path to the virtual card contents file.
    </xs:documentation>
  </xs:annotation>
  <xs:element name="control">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="show">
          <xs:annotation>
            <xs:documentation>
              The show element specifies the visibility of the virtual and physical readers.
            </xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="REAL_FIRST" />
              <xs:enumeration value="REAL_LAST" />
              <xs:enumeration value="HIDE_REAL" />
              <xs:enumeration value="HIDE_VIRTUAL" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="virtualcard" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>
              The virtualcard element specifies which virtual card to use
              for a physical test card. The hardchipnr element is the chip
              number (in hex) of the physical test card; the file element
              is the path to the virtual contents file.
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="hardchipnr" type="xs:string" />
              <xs:element name="file" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Fedict/eid-test-cards/client_software/client_software/_DocsInternal/BeidTestCtrl2.xml
<?xml version="1.0" encoding="UTF-8"?><control xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://env.dev.eid.belgium.be/eidtestinfra http://env.dev.eid.belgium.be/schemas/control.xsd"><show>REAL_LAST</show><virtualcard><hardchipnr>534C494E336600296CFF232CF7131030</hardchipnr><file>..//..//_DocsInternal//virtual_stephen.xml</file></virtualcard><virtualcard><hardchipnr>534C494E336600296CFF262368192F16</hardchipnr><file>..//..//_DocsInternal//virtual_flores.xml</file></virtualcard><virtualcard><hardchipnr>534C494E336600296CFF270DF4011318</hardchipnr><file>..//..//_DocsInternal//virtual_rogier.xml</file></virtualcard></control>

=== Fedict/eid-test-cards/client_software/client_software/_DocsInternal/BeidTestCtrl.xml
<?xml version="1.0" encoding="UTF-8"?>
<control xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://env.dev.eid.belgium.be/eidtestinfra http://env.dev.eid.belgium.be/schemas/control.xsd">
  <show>REAL_LAST</show>
  <virtualcard>
    <hardchipnr>534C494E336600296CFF232CF7131030</hardchipnr>    //Stephen
    <file>..//_DocsInternal//virtual_stephen.xml</file>
  </virtualcard>
  <virtualcard>
    <hardchipnr>534C494E336600296CFF270DF4011318</hardchipnr>    //Rogier
    <file>..//_DocsInternal//virtual_rogier.xml</file>
  </virtualcard>
  <virtualcard>
    <hardchipnr>534C494E336600296CFF262368192F16</hardchipnr>   //Flores
    <file>..//_DocsInternal//virtual_flores.xml</file>
  </virtualcard>
  <virtualcard>
    <hardchipnr>534C494E336600296CFF232CF7131033</hardchipnr>
    <file>C:/Documents And Settings/Stephen/virtual4.xml</file>
  </virtualcard>
  <virtualcard>
    <hardchipnr>534C494E336600296CFF232CF7131034</hardchipnr>
    <file>C:/Documents And Settings/Stephen/virtual4.xml</file>
  </virtualcard>
  <virtualcard>
    <hardchipnr>534C494E336600296CFF232CF7131035</hardchipnr>
    <file>C:/Documents And Settings/Stephen/virtual6.xml</file>
  </virtualcard>
</control>
